### ISSUE TITLE
FeedbackFrånGruppen

### ISSUE THREAD

**Issue by Timhavingfun03** [Idifixsmurfen/A_Mathematical_ADDventure#2]
* Koden är bra komenterad
* Blandar Svenska och Engelska
* Det är ett funktionellt matte spel
* Lite konstig strukturerad 
* Lite liten text
* Men förståligt och simpelt
* Mer skulle kunna ligga i "load funktionen"

**Comment by Idifixsmurfen** [comment]
Solved (Ish)
